# Generated by Django 5.2.5 on 2025-09-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('date_reg', models.DateField(auto_now_add=True)),
                ('date_read', models.DateField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('ano_publicacao', models.IntegerField(verbose_name='Ano de Publicação')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('edicao', models.CharField(blank=True, max_length=100, null=True)),
                ('paginas', models.PositiveIntegerField(verbose_name='Número de Páginas')),
                ('tema_principal', models.CharField(max_length=200, verbose_name='Tema Principal')),
                ('avaliacao_pessoal', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
