# Generated by Django 5.2.5 on 2025-09-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_book_user_alter_book_avaliacao_pessoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
